language: php
dist: trusty
sudo: false

branches:
  except:
  - l10n_2.4

php:
  - 7.1
  - 7.2

before_install:
  - cp .env.example .env
  - phpenv config-rm xdebug.ini

install: travis_retry composer install --no-interaction --no-suggest

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then vendor/bin/phpunit; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
